### ISSUE TITLE
Link to database using mongo

### ISSUE THREAD

**Issue by jack17529** [MaximStrutinskiy/NodeJS#1]
I am very new to all this , can you please tell me where is the data directory and how to connect it to the mongodb ?

**Comment by MaximStrutinskiy** [comment]
Hi @jack17529 , me to.
Look at this file: https://github.com/MaximStrutinskiy/NodeJS/blob/youtube/models/user.js ;

1) get mongoose tool for connection to DB
```var mongoose = require('mongoose');```
2) and hear you connecting to DB
```mongoose.connect('mongodb://localhost/nodeauth', {useMongoClient: true});```
